name: Build FluidDial

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: Build PlatformIO Project
        run: cd FluidDial && pio run && pio run -t buildfs
      - name: Upload Windows bundle
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: FluidDial/.pio/build/m5dial/*.bin
